
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fanky Abdilqoyyim
 */
public class roomFees extends javax.swing.JFrame {

    /**
     * Creates new form roomFees
     */
    public roomFees() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfEmail1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbPNumber = new javax.swing.JLabel();
        lbRType = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        lbDot1 = new javax.swing.JLabel();
        lbDot4 = new javax.swing.JLabel();
        lbDot5 = new javax.swing.JLabel();
        lbDot6 = new javax.swing.JLabel();
        lbDot7 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfPNumber = new javax.swing.JTextField();
        cbRType = new javax.swing.JComboBox<>();
        tfPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Room Rental Fees");

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setText("SIMPLE ROOM RENTAL FEES");

        lbName.setText("NAME");
        lbName.setName("NAME"); // NOI18N

        lbEmail.setText("EMAIL");
        lbEmail.setName("NAME"); // NOI18N

        lbPNumber.setText("PHONE NUMBER");
        lbPNumber.setName("NAME"); // NOI18N

        lbRType.setText("ROOM TYPE");
        lbRType.setName("NAME"); // NOI18N

        lbPrice.setText("PRICE");
        lbPrice.setName("NAME"); // NOI18N

        btnConfirm.setText("CONFIRM");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        lbDot1.setText(":");

        lbDot4.setText(":");

        lbDot5.setText(":");

        lbDot6.setText(":");

        lbDot7.setText(":");

        cbRType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a room...", "Standard Room", "Superior Room", "Deluxe Room", "Family Room" }));
        cbRType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbName)
                        .addGap(80, 80, 80)
                        .addComponent(lbDot1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfName))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEmail)
                            .addComponent(lbPNumber)
                            .addComponent(lbRType)
                            .addComponent(lbPrice))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbDot6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbDot7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbDot5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbRType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbDot4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPrice)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(btnConfirm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName)
                    .addComponent(lbDot1)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDot7)
                    .addComponent(lbEmail)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDot6)
                    .addComponent(lbPNumber)
                    .addComponent(tfPNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDot5)
                    .addComponent(lbRType)
                    .addComponent(cbRType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDot4)
                    .addComponent(lbPrice)
                    .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnConfirm)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        String name = tfName.getText();
        String email = tfEmail.getText();
        String phoneNumber = tfPNumber.getText();
        String room = cbRType.getSelectedItem().toString();
        String price = tfPrice.getText();
        
        int result = JOptionPane.showConfirmDialog(null, "Do you want to confirm this data?","Confirm", JOptionPane.YES_NO_OPTION);
        
        if (result == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null,
                    "Name\t\t: " + name 
                    + "\nEmail\t\t: " + email 
                    + "\nPhone Number\t: " + phoneNumber
                    + "\nRoom\t\t: " + room
                    + "\nPrice\t\t: " + price);
        } else {
            JOptionPane.showMessageDialog(null, "Sorry, your data was not confirmed😢");
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void cbRTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRTypeActionPerformed
        String room = cbRType.getSelectedItem().toString();
        
        switch (room){
            case "Standard Room" -> {
                tfPrice.setEditable(false);
                tfPrice.setText("Rp. 2.000.000,-");
            }
            case "Superior Room" -> {
                tfPrice.setEditable(false);
                tfPrice.setText("Rp. 3.000.000,-");
            }
            case "Deluxe Room" -> {
                tfPrice.setEditable(false);
                tfPrice.setText("Rp. 5.000.000,-");
            }
            case "Family Room" -> {
                tfPrice.setEditable(false);
                tfPrice.setText("Rp. 3.500.000,-");
            }
            default -> {
                tfPrice.setEditable(false);
                tfPrice.setText("");
            }
        }
    }//GEN-LAST:event_cbRTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new roomFees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox<String> cbRType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbDot1;
    private javax.swing.JLabel lbDot4;
    private javax.swing.JLabel lbDot5;
    private javax.swing.JLabel lbDot6;
    private javax.swing.JLabel lbDot7;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPNumber;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbRType;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEmail1;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPNumber;
    private javax.swing.JTextField tfPrice;
    // End of variables declaration//GEN-END:variables
}
